package main

type FileFieldInfo struct {
	Source   string
	Package  string
	Name     string
	Messages []MessageFieldInfo
}
type MessageFieldInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Name  string
	Field string
}

var fieldTemplate = `
// Code generated by protoc-gen-gorm. DO NOT EDIT.
// source: {{ .Source }}

package {{ .Package }}

type xfields{{ .Name }} struct {
	{{ range .Messages }} {{ .Name }} filedsOf{{ .Name }}  
	{{ end }}
}

{{ range .Messages }}
type filedsOf{{ .Name }} struct {
	{{ range .Fields }} {{ .Name }} string
	{{ end }}
}
{{  end }}

var (
	{{ .Name }}Fields = xfields{{ .Name }}{ 
		{{ range .Messages }} {{ .Name }}: filedsOf{{ .Name }} { 
			{{ range .Fields }} {{ .Name }} : "{{ .Field }}",
			{{ end }}
		},
		{{ end }}
	}
)
`
